In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("diabetes (1).csv") # Pima Indian Diabtes Database

In [3]:
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
import numpy as np


cols_fix = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']


df[cols_fix] = df[cols_fix].replace(0, np.nan)

In [7]:
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,NaN,NaN,25.6,0.201,30,0
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
7,10,115.0,NaN,NaN,NaN,35.3,0.134,29,0
8,2,197.0,70.0,45.0,543.0,30.5,0.158,53,1
9,8,125.0,96.0,NaN,NaN,NaN,0.232,54,1

In [ ]:

df['Glucose'].fillna(df['Glucose'].median(), inplace=True)
df['BloodPressure'].fillna(df['BloodPressure'].median(), inplace=True)
df['BMI'].fillna(df['BMI'].median(), inplace=True)


df['Insulin'].fillna(df['Insulin'].median(), inplace=True)
df['SkinThickness'].fillna(df['SkinThickness'].median(), inplace=True)

C:\Users\Gurneet Singh\AppData\Local\Temp\ipykernel_12408\4116122362.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Glucose'].fillna(df['Glucose'].median(), inplace=True)
C:\Users\Gurneet Singh\AppData\Local\Temp\ipykernel_12408\4116122362.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BloodPressure'].fillna(df['BloodPressure'].median(), inplace=True)
C:\Users\Gurneet Singh\AppData\Local\Temp\ipykernel_12408\4116122362.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BMI'].fillna(df['BMI'].median(), inplace=True)
C:\Users\Gurneet Singh\AppData\Local\Temp\ipykernel_12408\4116122362.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Insulin'].fillna(df['Insulin'].median(), inplace=True)
C:\Users\Gurneet Singh\AppData\Local\Temp\ipykernel_12408\4116122362.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['SkinThickness'].fillna(df['SkinThickness'].median(), inplace=True)

In [9]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [10]:
df.drop("Insulin",axis=1,inplace=True)

In [11]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,43.1,2.288,33,1

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [13]:
update1 = df.drop("Outcome",axis=1)

In [14]:
update1

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age
0,6,148.0,72.0,35.0,33.6,0.627,50
1,1,85.0,66.0,29.0,26.6,0.351,31
2,8,183.0,64.0,29.0,23.3,0.672,32
3,1,89.0,66.0,23.0,28.1,0.167,21
4,0,137.0,40.0,35.0,43.1,2.288,33
...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,32.9,0.171,63
764,2,122.0,70.0,27.0,36.8,0.340,27
765,5,121.0,72.0,23.0,26.2,0.245,30
766,1,126.0,60.0,29.0,30.1,0.349,47
767,1,93.0,70.0,31.0,30.4,0.315,23

In [15]:
df2 = sc.fit(update1)

In [16]:
df2 = sc.transform(update1)

In [17]:
df2

array([[ 0.63994726,  0.86604475, -0.03198993, ...,  0.16661938,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.20506583, -0.5283186 , ..., -0.85219976,
        -0.36506078, -0.19067191],
       [ 1.23388019,  2.01666174, -0.69376149, ..., -1.33250021,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 , -0.02157407, -0.03198993, ..., -0.910418  ,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.14279979, -1.02464727, ..., -0.34279019,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.94206766, -0.19743282, ..., -0.29912651,
        -0.47378505, -0.87137393]], shape=(768, 7))

In [18]:
df[["Pregnancies","Glucose","BloodPressure","SkinThickness", "BMI",	"DiabetesPedigreeFunction"	,"Age"]] = df2

In [19]:
df.drop("SkinThickness",axis=1,inplace=True)
df

,Pregnancies,Glucose,BloodPressure,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.639947,0.866045,-0.031990,0.166619,0.468492,1.425995,1
1,-0.844885,-1.205066,-0.528319,-0.852200,-0.365061,-0.190672,0
2,1.233880,2.016662,-0.693761,-1.332500,0.604397,-0.105584,1
3,-0.844885,-1.073567,-0.528319,-0.633881,-0.920763,-1.041549,0
4,-1.141852,0.504422,-2.679076,1.549303,5.484909,-0.020496,1
...,...,...,...,...,...,...,...
763,1.827813,-0.679069,0.298896,0.064737,-0.908682,2.532136,0
764,-0.547919,0.011301,-0.197433,0.632365,-0.398282,-0.531023,0
765,0.342981,-0.021574,-0.031990,-0.910418,-0.685193,-0.275760,0
766,-0.844885,0.142800,-1.024647,-0.342790,-0.371101,1.170732,1
767,-0.844885,-0.942068,-0.197433,-0.299127,-0.473785,-0.871374,0

In [20]:
df.drop("BloodPressure",axis=1,inplace=True)
df

,Pregnancies,Glucose,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.639947,0.866045,0.166619,0.468492,1.425995,1
1,-0.844885,-1.205066,-0.852200,-0.365061,-0.190672,0
2,1.233880,2.016662,-1.332500,0.604397,-0.105584,1
3,-0.844885,-1.073567,-0.633881,-0.920763,-1.041549,0
4,-1.141852,0.504422,1.549303,5.484909,-0.020496,1
...,...,...,...,...,...,...
763,1.827813,-0.679069,0.064737,-0.908682,2.532136,0
764,-0.547919,0.011301,0.632365,-0.398282,-0.531023,0
765,0.342981,-0.021574,-0.910418,-0.685193,-0.275760,0
766,-0.844885,0.142800,-0.342790,-0.371101,1.170732,1
767,-0.844885,-0.942068,-0.299127,-0.473785,-0.871374,0

In [21]:
X=df.drop('Outcome',axis=1)
Y=df['Outcome']

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_text,y_train,y_test = train_test_split(X,Y,test_size=0.2)

In [23]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [24]:
Lmodel = lr.fit(x_train,y_train)

In [25]:
Lpred = Lmodel.predict(x_text)

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,Lpred)
cm

array([[88, 16],
       [14, 36]])

In [27]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print(accuracy_score(y_test,Lpred))
print(precision_score(y_test,Lpred))
print(recall_score(y_test,Lpred))
print(f1_score(y_test,Lpred))

0.8051948051948052
0.6923076923076923
0.72
0.7058823529411765

In [ ]:
import joblib
joblib.dump(Lmodel,"dibates.joblib")